### PR TITLE
Sub directory style tags, apache style config, some doc changes

### PR DESCRIPTION
**Pull request by djzort**
This PR includes two fairly minor things and one quite large one.

Firstly, enable a bunch of options in Config::General around enabling the 'include' function. The updated selection of options allows the 'include' verb with directories and globs and allows config fragments to be loaded over and over. 

This permits for a parent repositorio.conf with something like repositorio.d/*conf to load in all the repo definitions. Handy for scripting and what not.

Secondly, the "all" keyword for repos is now documented and if found in the repositorio.conf you get a nasty error message.

Third, introduces a config option that places the tag directory at the bottom most directory rather than the top. There are pros and cons to top or bottom directory tags - which is briefly touched on in the commit message. Bottom directory style tags make much more sense for us. In the process, i also converted most path handling (if not all) to using File::Spec.

### CODE REVIEW

**Comment by djzort** [comment]
I was going to use File::Temp to magically create a private temporary directory too... but the change is big enough as it is and i want to get a feel for whats going to be accepted.

**Comment by djzort** [comment]
ping?

**Comment by krimdomu** [comment]
@djzort sorry for the delay, but i still having problems with my handwrists... :(

**Comment by djzort** [comment]
is there others that can sign off or otherwise push this back for refinement?

**Comment by djzort** [comment]
i know youre in pain, is there someone else who can look at this?

**Comment by krimdomu** [comment]
Hi @djzort,

sorry for the delay and thank you for this patch. I'm now able to to some things again, so I'm going to merge it and take a look at the other pr's so i can create a new release in the near futue.

**Comment by djzort** [comment]
ok thanks for that. I hope you are recovering well.

**Pull request merged**
